### PR TITLE
Use Ranch for TCP acceptor pool

### PR DESCRIPTION
**Pull request by essen**
Part of https://github.com/rabbitmq/rabbitmq-server/issues/260.

### CODE REVIEW

**Comment by essen** [comment]
The tests fail on that one. Will fix.

**Comment by michaelklishin** [comment]
After merging master into this branch, all tests pass on OS X and Linux.

**Comment by essen** [comment]
Rebased against master and edited the commit message.

**Comment by michaelklishin** [comment]
Testing GH notifications.

**Pull request merged**
